name: Develop

on:
  push:
    branches: 
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    container: lfenergy/arras:latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate data
      run: ./autotest
      
    - name: Save results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: autotest-results.tarz
        path: autotest-results.tarz
